### ISSUE TITLE
有2个问题

### ISSUE THREAD

**Issue by salmanit** [rokudol/PswText#1]
![show](https://user-images.githubusercontent.com/6285702/29393220-32454696-8335-11e7-8dca-710352ffaa02.png)
我的手机上看到的效果是这样，上下左右四个边，明显看到上边那个细了很多，第一个我啥额外属性都没设置，麻烦有空的时候给看下，个人猜测应该是少计算了画笔的宽度，top位置弄个0，画笔宽度为3，那1.5的宽度就跑到屏幕外边去了。

另外//The roundness of the border is 8dp 注释的这行代码是不是放错地方了，因为上边获取属性后这里又设置为固定的8dp，那布局里设置圆角就没效果了。

**Comment by rokudol** [comment]
@salmanit 非常感谢帮忙找出问题，这两天公司开发比较忙，周末我会看一下，然后进行修改，注释问题我周末也会更改为中文。。之前是为了提交到jcenter修改为英文的

**Comment by rokudol** [comment]
@salmanit bug已解决，并发布了新版本，新增了功能

**Comment by salmanit** [comment]
谢谢你分享源码，刚好需要一个输入验证码的，就看到这个，顺道就放进代码了。^_^

**Comment by rokudol** [comment]
@salmanit 不客气！能帮到你就是我的荣幸了！
