### ISSUE TITLE
输入框中的文字不居中

### ISSUE THREAD

**Issue by cjpx00008** [rokudol/PswText#4]
在我的手机上测试的时候发现输入框的文字不居中，楼主drawText的时候用的textbounds来测量文字的宽度，我改成measureText测量的宽度来绘制之后，就正常了

**Comment by rokudol** [comment]
所有机型都是这样吗？我自己测试没有发现过这个问题

**Comment by rokudol** [comment]
@cjpx00008 所有机型都是这样吗？我自己测试并没有发现这个问题
