### ISSUE TITLE
密码输入完成有监听吗

### ISSUE THREAD

**Issue by DuZhengLin17** [rokudol/PswText#5]
密码输入完成有监听吗，或者说 输入时 有监听吗？

**Comment by rokudol** [comment]
@DuZhengLin17 输入完成时，会触发InputCallBack，回调用户输入的密码

**Comment by DuZhengLin17** [comment]
可是   如果用户输入完成又删了 能监听到吗？

**Comment by rokudol** [comment]
@DuZhengLin17 印象中是没问题的，如果有问题请告知

**Comment by DuZhengLin17** [comment]
我指的是这个意思的    比如4位密码 1234   因为输入完成 所以开放了下一步  然后 他又删了一位变成123  可是我的下一步已经开放了 应该怎么做了 谢谢大佬指点

**Comment by rokudol** [comment]
@DuZhengLin17 下一步如果是切换页面或请求接口等操作的话，用户没有可删除密码的操作空间，如果只是隐藏键盘，并在点击“确认”按钮才提交密码的话，可调用getPsw()函数，判断length是否等于密码总长度

**Comment by DuZhengLin17** [comment]
是这样的 比如   四位密码    下一步是灰色的  因为InputCallBack 正式完成时触发    
所以就会有这种情况 我输入1234 触发了  然后   下一步按钮变颜色了变成黄色  但是用户又删了一个 变成三位了  可是下一步还是 黄色 这就有点尴尬了

**Comment by rokudol** [comment]
@DuZhengLin17 clone源码，自己实现一个输入中的监听，或等我有空的时候更新个版本

**Comment by DuZhengLin17** [comment]
好的 谢谢大佬

**Comment by rokudol** [comment]
@DuZhengLin17 已更新版本，具体调用方式查看README
